version: '3.8'

services:
  app:
    container_name: vanna-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8084"
    env_file:
      - .env
    environment:
      - DB_TYPE=${DB_TYPE:-postgres}
      - DB_HOST=vanna-postgres
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT:-5432}
      # - CHROMA_HOST=vanna-chromadb
      # - CHROMA_PORT=${CHROMA_PORT:-8000}
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    container_name: vanna-postgres
    image: postgres:17
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data-poc:/var/lib/postgresql/data
    networks:
      - app-network

  # chromadb:
  #   container_name: vanna-chromadb
  #   image: chromadb/chroma:latest
  #   ports:
  #     - "${CHROMA_PORT:-8000}:8000"
  #   volumes:
  #     - chroma-data-poc:/chroma/chroma
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
  #     interval: 60s
  #     timeout: s
  #     retries: 5
  #   networks:
  #     - app-network

networks:
  app-network:
    name: vanna-network
    driver: bridge

volumes:
  postgres-data-poc:
  # chroma-data-poc: 